# Generated by Django 4.2.19 on 2025-04-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='movie.film')),
            ],
            options={
                'unique_together': {('film', 'language_code')},
            },
        ),
    ]
